# Generated by Django 2.2.19 on 2022-05-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220509_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='Default', max_length=30),
            preserve_default=False,
        ),
    ]
